[[redirects]]
  from = "/qr"
  to = "https://taikai.network/ethbrussels/hackathons/ETHBrussels"

[[redirects]]
  from = "/hackers"
  to = "https://taikai.network/ethbrussels/hackathons/ETHBrussels"

[[redirects]]
  from = "/taikai"
  to = "https://taikai.network/ethbrussels/hackathons/ETHBrussels"

[[redirects]]
  from = "/sponsors"
  to = "https://daobrussels.notion.site/Sponsoring-ETH-Brussels-9888d22f7e33423db617c3014b26b98b"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/u2e6Prvp5T"

[[redirects]]
  from = "/*"
  to = "https://blockchainweek.be/eth-brussels"
