[[redirects]]
  from = "/qr"
  to = "https://taikai.network/ethbrussels/hackathons/ETHBrussels"

[[redirects]]
  from = "/hackers"
  to = "https://taikai.network/ethbrussels/hackathons/ETHBrussels"

[[redirects]]
  from = "/taikai"
  to = "https://taikai.network/ethbrussels/hackathons/ETHBrussels"

[[redirects]]
  from = "/sponsors"
  to = "https://daobrussels.notion.site/Sponsoring-ETH-Brussels-9888d22f7e33423db617c3014b26b98b"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/u2e6Prvp5T"

[[redirects]]
  from = "/schedule"
  to = "https://airtable.com/shr2ikJtdfgOivKxj/tbl0S3ql1nq9Z2xUN"

[[redirects]]
  from = "/add-to-schedule"
  to = "https://tally.so/r/mRd5L4"

[[redirects]]
  from = "/*"
  to = "https://linktr.ee/ethbrussels"

[[redirects]]
  from = "/*"
  to = "https://blockchainweek.be/eth-brussels"
